### ISSUE TITLE
Allow for unformatted JSON

### ISSUE THREAD

**Issue by caal-15** [OutOfSyncStudios/winston-logstash-transport#2]
I found this tool really useful, But noticed that it doesn't allow you to log your `info` object as plain JSON, but instead formats it, that would be a really useful feature :)

**Comment by chronosis** [comment]
Please see the updates to the README.md file and regarding the `formatted` option which was added. You will need to explicitly set this option to `false` in the set up of the transport. 

```js
const Winston = require('winston');
const WinstonLogStash = require('winston3-logstash-transport');
 
const logger = Winston.createLogger();
 
logger.add(new WinstonLogStash({
  mode: 'udp',
  host: '127.0.0.1',
  port: 28777,
  formatted: false
}));
```

Thank you for the PR, I used it as a guide. Unfortunately, the PR itself was too problematic to be used in the way it was provided. Therefore we implemented the changes directly and include documentation and pushed it through our build/release cycle.

**Comment by caal-15** [comment]
Hey @chronosis, Thanks for listening!, I'm just glad the feature is in now :)

**Comment by caal-15** [comment]
Hey @chronosis, apparently the feature did not go into the latest release on NPM, downloading the latest version there returns the old index.js file which does not have the formatted flag :(
