### ISSUE TITLE
The npm package has not been updated (to 1.1.0)

### ISSUE THREAD

**Issue by Eseeelil-dev** [OutOfSyncStudios/winston-logstash-transport#4]
Current version of [npm package](https://www.npmjs.com/package/winston3-logstash-transport) is 1.0.1-c but master branch has 1.1.0.

I believe that the npm package version should also be updated.

**Comment by amcereijo** [comment]
The last changes are not published so the README file does not match with the actual published behavior

**Comment by ryandanielspmc** [comment]
@chronosis Is there an idea of when this will be completed?

**Comment by mnebuerquo** [comment]
There hasn't been any activity on this repo in over a year now. It appears to be abandoned.
